packages:
  # specify a package in a direct subdir of the root
  - 'apps/*'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - '!packages/drivers'
  # exclude packages that are inside test directories
  - '!**/test/**'
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true


nodeLinker: hoisted
blockExoticSubdeps: false

packageExtensions:
  vite-plugin-electron:
    peerDependencies:
      electron: "*"
